### ISSUE TITLE
Map data is not cleared on disconnect/shutdown

### ISSUE THREAD

**Issue by sleepingdragoninn** [HestiMae/hoofprint#4]
swapping between singleplayer worlds can lead to:

![image](https://github.com/user-attachments/assets/d6589154-8f08-48c3-b120-1641ff44de3b)

**Comment by 800020h** [comment]
I think this is the same issue
![2024-08-16_21 23 48](https://github.com/user-attachments/assets/b21859f6-f483-4bf6-9e79-6652dbf20f16)
in world 2 seeing map and magenta marker from world 1
\---
![2024-08-16_21 24 25](https://github.com/user-attachments/assets/efa8a248-9145-45e3-9fe3-d204adb34dae)
in world 1 seeing map and death point from world 2
\---
![2024-08-16_21 24 54](https://github.com/user-attachments/assets/281e9f99-d5a8-425d-a34d-0c69242ca79f)
in world 1 seeing death point from world 2 didn't get removed when the world 1 map was redrawn
